import { normalizeAnswer } from "../answerMatching.ts";
import { pinyin } from "pinyin-pro";

type ParsedSyllable = {
  final: string;
  initial: string;
  raw: string;
};

const INITIALS = [
  "zh",
  "ch",
  "sh",
  "b",
  "p",
  "m",
  "f",
  "d",
  "t",
  "n",
  "l",
  "g",
  "k",
  "h",
  "j",
  "q",
  "x",
  "r",
  "z",
  "c",
  "s",
  "y",
  "w",
];

const INITIAL_CONFUSIONS = new Set([
  "z:zh",
  "c:ch",
  "s:sh",
  "n:l",
  "f:h",
  "d:t",
  "g:k",
  "j:q",
  "x:sh",
]);

const FINAL_CONFUSIONS = new Set([
  "an:ang",
  "en:eng",
  "in:ing",
  "ian:iang",
  "uan:uang",
  "n:ng",
  "ou:uo",
  "ei:ui",
]);

const PHRASE_PINYIN_OVERRIDES: Record<string, string[]> = {
  阿柏蛇: ["a", "bo", "she"],
  阿柏怪: ["a", "bo", "guai"],
};

const PINYIN_BY_CHAR: Record<string, string> = {
  阿: "a",
  八: "ba",
  巴: "ba",
  叭: "ba",
  霸: "ba",
  百: "bai",
  白: "bai",
  柏: "bai",
  斑: "ban",
  板: "ban",
  判: "pan",
  胖: "pang",
  暴: "bao",
  宝: "bao",
  贝: "bei",
  貝: "bei",
  比: "bi",
  边: "bian",
  邊: "bian",
  变: "bian",
  變: "bian",
  扁: "bian",
  标: "biao",
  别: "bie",
  冰: "bing",
  波: "bo",
  卜: "bo",
  布: "bu",
  步: "bu",
  部: "bu",
  擦: "ca",
  猜: "cai",
  蚕: "can",
  草: "cao",
  超: "chao",
  虫: "chong",
  唇: "chun",
  穿: "chuan",
  葱: "cong",
  蔥: "cong",
  刺: "ci",
  磁: "ci",
  催: "cui",
  达: "da",
  達: "da",
  大: "da",
  呆: "dai",
  袋: "dai",
  带: "dai",
  刀: "dao",
  蛋: "dan",
  弹: "dan",
  彈: "dan",
  丁: "ding",
  定: "ding",
  钉: "ding",
  釘: "ding",
  冻: "dong",
  蚪: "dou",
  地: "di",
  迪: "di",
  蒂: "di",
  嘟: "du",
  电: "dian",
  電: "dian",
  雕: "diao",
  叠: "die",
  蝶: "die",
  毒: "du",
  独: "du",
  獨: "du",
  多: "duo",
  娥: "e",
  蛾: "e",
  偶: "ou",
  发: "fa",
  飞: "fei",
  飛: "fei",
  肥: "fei",
  風: "feng",
  风: "feng",
  蜂: "feng",
  凤: "feng",
  福: "fu",
  符: "fu",
  蝠: "fu",
  嘎: "ga",
  尕: "ga",
  盖: "gai",
  怪: "guai",
  乖: "guai",
  归: "gui",
  规: "gui",
  鬼: "gui",
  龜: "gui",
  龟: "gui",
  跟: "gen",
  耿: "geng",
  更: "geng",
  哥: "ge",
  狗: "gou",
  够: "gou",
  固: "gu",
  呱: "gua",
  哈: "ha",
  豪: "hao",
  海: "hai",
  憨: "han",
  合: "he",
  后: "hou",
  侯: "hou",
  喉: "hou",
  猴: "hou",
  胡: "hu",
  花: "hua",
  化: "hua",
  画: "hua",
  幻: "huan",
  火: "huo",
  甲: "jia",
  箭: "jian",
  角: "jiao",
  吉: "ji",
  急: "ji",
  击: "ji",
  擊: "ji",
  基: "ji",
  鸡: "ji",
  杰: "jie",
  傑: "jie",
  姐: "jie",
  金: "jin",
  进: "jin",
  精: "jing",
  九: "jiu",
  菊: "ju",
  巨: "ju",
  觉: "jue",
  君: "jun",
  卡: "ka",
  凯: "kai",
  凱: "kai",
  开: "kai",
  克: "ke",
  可: "ke",
  壳: "ke",
  殼: "ke",
  肯: "ken",
  蝌: "ke",
  口: "kou",
  恐: "kong",
  快: "kuai",
  块: "kuai",
  盔: "kui",
  拉: "la",
  啦: "la",
  喇: "la",
  赖: "lai",
  兰: "lan",
  蘭: "lan",
  螂: "lang",
  朗: "lang",
  郎: "lang",
  老: "lao",
  雷: "lei",
  冷: "leng",
  烈: "lie",
  厘: "li",
  利: "li",
  力: "li",
  鲤: "li",
  鯉: "li",
  栗: "li",
  莉: "li",
  裡: "li",
  里: "li",
  镰: "lian",
  六: "liu",
  隆: "long",
  龍: "long",
  龙: "long",
  路: "lu",
  陆: "lu",
  鲁: "lu",
  魯: "lu",
  鹿: "lu",
  罗: "luo",
  羅: "luo",
  洛: "luo",
  螺: "luo",
  绿: "lv",
  玛: "ma",
  瑪: "ma",
  马: "ma",
  馬: "ma",
  麦: "mai",
  毛: "mao",
  猫: "mao",
  貓: "mao",
  喵: "miao",
  苗: "miao",
  妙: "miao",
  迷: "mi",
  咪: "mi",
  眠: "mian",
  绵: "mian",
  墨: "mo",
  摩: "mo",
  魔: "mo",
  貘: "mo",
  母: "mu",
  木: "mu",
  娜: "na",
  你: "ni",
  尼: "ni",
  泥: "ni",
  念: "nian",
  鸟: "niao",
  鳥: "niao",
  牛: "niu",
  诺: "nuo",
  諾: "nuo",
  怕: "pa",
  派: "pai",
  盘: "pan",
  皮: "pi",
  霹: "pi",
  噼: "pi",
  喷: "pen",
  普: "pu",
  七: "qi",
  奇: "qi",
  蔓: "man",
  钳: "qian",
  鉗: "qian",
  墙: "qiang",
  牆: "qiang",
  丘: "qiu",
  秋: "qiu",
  球: "qiu",
  拳: "quan",
  犬: "quan",
  染: "ran",
  人: "ren",
  日: "ri",
  绒: "rong",
  肉: "rou",
  瑞: "rui",
  三: "san",
  瑙: "nao",
  森: "sen",
  沙: "sha",
  山: "shan",
  闪: "shan",
  舌: "she",
  蛇: "she",
  身: "shen",
  石: "shi",
  士: "shi",
  食: "shi",
  始: "shi",
  狮: "shi",
  獅: "shi",
  十: "shi",
  手: "shou",
  兽: "shou",
  獸: "shou",
  受: "shou",
  树: "shu",
  樹: "shu",
  鼠: "shu",
  双: "shuang",
  雙: "shuang",
  水: "shui",
  睡: "shui",
  斯: "si",
  速: "su",
  素: "su",
  蒜: "suan",
  泰: "tai",
  螳: "tang",
  特: "te",
  藤: "teng",
  疼: "teng",
  天: "tian",
  铁: "tie",
  鐵: "tie",
  通: "tong",
  头: "tou",
  頭: "tou",
  腿: "tui",
  瓦: "wa",
  蛙: "wa",
  娃: "wa",
  腕: "wan",
  顽: "wan",
  王: "wang",
  旺: "wang",
  汪: "wang",
  蚊: "wen",
  问: "wen",
  我: "wo",
  西: "xi",
  希: "xi",
  吸: "xi",
  犀: "xi",
  膝: "xi",
  小: "xiao",
  香: "xiang",
  象: "xiang",
  向: "xiang",
  星: "xing",
  幸: "xing",
  醒: "xing",
  胸: "xiong",
  雄: "xiong",
  兄: "xiong",
  袖: "xiu",
  臭: "xiu",
  休: "xiu",
  需: "xu",
  玄: "xuan",
  鸭: "ya",
  鴨: "ya",
  呀: "ya",
  芽: "ya",
  岩: "yan",
  眼: "yan",
  焰: "yan",
  颜: "yan",
  羊: "yang",
  痒: "yang",
  妖: "yao",
  椰: "ye",
  一: "yi",
  伊: "yi",
  翼: "yi",
  异: "yi",
  異: "yi",
  音: "yin",
  引: "yin",
  勇: "yong",
  泳: "yong",
  蛹: "yong",
  鱼: "yu",
  魚: "yu",
  羽: "yu",
  玉: "yu",
  园: "yuan",
  圆: "yuan",
  运: "yun",
  運: "yun",
  尾: "wei",
  杂: "za",
  蚤: "zao",
  早: "zao",
  藻: "zao",
  贼: "zei",
  眨: "zha",
  长: "zhang",
  障: "zhang",
  掌: "zhang",
  针: "zhen",
  針: "zhen",
  阵: "zhen",
  真: "zhen",
  正: "zheng",
  只: "zhi",
  种: "zhong",
  種: "zhong",
  仲: "zhong",
  周: "zhou",
  走: "zou",
  嘴: "zui",
  子: "zi",
  籽: "zi",
  仔: "zi",
  紫: "zi",
  钻: "zuan",
  鑽: "zuan",
  雳: "li",
  雀: "que",
  蟹: "xie",
  梦: "meng",
};

function splitInitial(syllable: string): ParsedSyllable {
  const initial = INITIALS.find((item) => syllable.startsWith(item)) || "";
  return {
    final: initial ? syllable.slice(initial.length) : syllable,
    initial,
    raw: syllable,
  };
}

function pairKey(left: string, right: string) {
  return [left, right].sort().join(":");
}

function simpleSimilarity(left: string, right: string) {
  if (left === right) return 1;
  const maxLength = Math.max(left.length, right.length);
  if (!maxLength) return 1;

  let same = 0;
  for (let index = 0; index < Math.min(left.length, right.length); index += 1) {
    if (left[index] === right[index]) same += 1;
  }

  return same / maxLength;
}

function initialSimilarity(left: string, right: string) {
  if (left === right) return 1;
  if (INITIAL_CONFUSIONS.has(pairKey(left, right))) return 0.82;
  if (!left || !right) return 0.25;
  return 0;
}

function finalSimilarity(left: string, right: string) {
  if (left === right) return 1;
  if (FINAL_CONFUSIONS.has(pairKey(left, right))) return 0.82;
  return simpleSimilarity(left, right) * 0.72;
}

export function toPinyinSyllables(value: string) {
  const normalized = normalizeAnswer(value);
  const override = PHRASE_PINYIN_OVERRIDES[normalized];
  if (override) return override;

  return (normalized.match(/\p{Script=Han}+|[a-z0-9]+/giu) || [])
    .flatMap((token) => {
      if (/^[a-z0-9]+$/i.test(token)) return [token.toLowerCase()];
      return pinyin(token, { toneType: "none", type: "array" });
    })
    .map((syllable) => syllable.toLowerCase().replaceAll("ü", "v"))
    .filter(Boolean);
}

export function pinyinSyllableSimilarity(left: string, right: string) {
  if (left === right) return 1;

  const parsedLeft = splitInitial(left);
  const parsedRight = splitInitial(right);
  const initialScore = initialSimilarity(parsedLeft.initial, parsedRight.initial);
  const finalScore = finalSimilarity(parsedLeft.final, parsedRight.final);

  return initialScore * 0.35 + finalScore * 0.65;
}

export function pinyinSequenceSimilarity(left: string[], right: string[]) {
  if (!left.length || !right.length) return 0;

  const rows = Array.from({ length: left.length + 1 }, () => Array(right.length + 1).fill(0));
  for (let row = 0; row <= left.length; row += 1) rows[row][0] = row;
  for (let column = 0; column <= right.length; column += 1) rows[0][column] = column;

  for (let row = 1; row <= left.length; row += 1) {
    for (let column = 1; column <= right.length; column += 1) {
      const substituteCost = 1 - pinyinSyllableSimilarity(left[row - 1], right[column - 1]);
      rows[row][column] = Math.min(
        rows[row - 1][column] + 1,
        rows[row][column - 1] + 1,
        rows[row - 1][column - 1] + substituteCost,
      );
    }
  }

  return Math.max(0, 1 - rows[left.length][right.length] / Math.max(left.length, right.length));
}
